version: '2.2'
services:
  ############################################## NGINX ##############################################
  nginx:
    container_name: 'nginx'
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/Dockerfile-nginx
      args: 
        NGINX_VERSION: ${NGINX_VERSION}
    ports: 
      - 80:80       # Splunk
      - 443:443     # Splunk
      - 8089:8089   # Splunk API
    networks: 
      - default
      - splunk-backend
      - kafka-backend
    depends_on: 
      - splunk
      - connect
      - control-center
      - rest-proxy
      - ksqldb-server
    cpus: 1
    mem_limit: 100M

  ############################################## Splunk ##############################################
  splunk:
    build: 
      context: .
      dockerfile: docker/Dockerfile-splunk
      args:
        SPLUNK_VERSION: ${SPLUNK_VERSION}
    restart: unless-stopped
    container_name: splunk
    networks:
      - splunk-backend
    environment:
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Changeme123!
    volumes: 
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    cpus: 8
    mem_limit: 12G

volumes:
  splunk-var:
  splunk-etc:

networks: 
  kafka-backend:
    external: true

