version: '2.2'
services:
  ############################################## Logstash ##############################################
  logstash:
    container_name: 'logstash'
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/Dockerfile-logstash
      args:
        LOGSTASH_VERSION: ${LOGSTASH_VERSION}
    ports: 
      - 5044:5044/tcp
    networks: 
      - default
      - logstash-backend
      - splunk-backend
    depends_on: 
      - splunk
      - broker
    cpus: 4
    mem_limit: 2G
    
networks: 
  logstash-backend:
  splunk-prod_kafka-backend:
    external: true