version: '2.2'
services:
  ############################################## Splunk ##############################################
  splunk:
    build: 
      context: .
      dockerfile: docker/Dockerfile-splunk
      args:
        SPLUNK_VERSION: ${SPLUNK_VERSION}
    restart: unless-stopped
    container_name: splunk
    networks:
      - default
      - splunk-backend
    ports:
      - 8000:8000
    environment:
      - SPLUNK_START_ARGS="--accept-license"
      - SPLUNK_PASSWORD=Changeme123!
    volumes: 
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    cpus: 8
    mem_limit: 12G

volumes: 
  splunk-var:
  splunk-etc:

networks: 
  splunk-backend:

