ARG LOGSTASH_VERSION
FROM logstash:${LOGSTASH_VERSION}

# Install plugins
RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-relp

# Copy certs
COPY conf/logstash/ssl/logstash.crt /usr/share/logstash/ssl/logstash.crt
COPY conf/logstash/ssl/logstash.key /usr/share/logstash/ssl/logstash.key

# Copy logstash.yml
RUN rm -rf /usr/share/logstash/pipeline/logstash.conf
COPY conf/logstash/logstash.yml /usr/share/logstash/config/logstash.yml

# Copy pipeline configs
COPY conf/logstash/pipeline/ /usr/share/logstash/pipeline